language: node_js
node_js:
  - 14.16.0
cache:
  yarn install
  
script:
  - yarn test 
  - yarn run build 

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages // ignorer le nettoyage pour pas que nos fichiers de construction soit supprime
  skip-cleanup: true
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments  pour conserver les anciens builds/fichiers des déploiements précédents
  keep-history: true
  local_dir: build
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
  on:
    # Which branch on commit/push will trigger deployment
    branch: master