language: node_js
node_js:
  - 14.16.0
cache:
  yarn install
  
script:
  - yarn test 
  - yarn run build # Generate static HTML files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master